### ISSUE TITLE
AttributeError: module 'streamlit.runtime.caching' has no attribute 'save_widget_metadata'

### ISSUE THREAD

**Issue by klentabistado** [LinXueyuanStdio/streamlit-markdown#3]
I am getting this error: AttributeError: module 'streamlit.runtime.caching' has no attribute 'save_widget_metadata'.

**Comment by liunux4odoo** [comment]
install `streamlit==1.37.1`, only this version has the function 'save_widget_metadata'

**Comment by LinXueyuanStdio** [comment]
it's a little tricky to use `save_widget_metadata` to hack streamlit, so that we can prevent re-rendering the entire component during streaming. Such hacky feature is related to the specific version of streamlit, as is pointed out by @liunux4odoo .   Anyway, I would find another way to keep pace with newer versions of streamlit. Keep in touch!

**Comment by LinXueyuanStdio** [comment]
fixed in the newest release
